In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

wine = load_wine()
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3, random_state=42)

model_knn = KNeighborsClassifier()
model_knn.fit(x_train, y_train)
y_pred_knn = model_knn.predict(x_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f'Accuracy KNN: {accuracy_knn}')

precision_knn = precision_score(y_test, y_pred_knn, average='weighted')
print(f'Precision KNN: {precision_knn}')

recall_knn = recall_score(y_test, y_pred_knn, average='weighted')
print(f'Recall KNN: {recall_knn}')

f1_knn = f1_score(y_test, y_pred_knn, average='weighted')
print(f'F1 Score KNN: {f1_knn}')

confusion_knn = confusion_matrix(y_test, y_pred_knn)
print(f'Confusion Matrix KNN:\n{confusion_knn}')

Accuracy KNN: 0.7407407407407407
Precision KNN: 0.7447530864197531
Recall KNN: 0.7407407407407407
F1 Score KNN: 0.7424072516587236
Confusion Matrix KNN:
[[17  0  2]
 [ 1 15  5]
 [ 1  5  8]]


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score
import numpy as np

housing = fetch_california_housing()
x = pd.DataFrame(housing.data, columns=housing.feature_names)
y = pd.Series(housing.target, name='MedHouseVal')

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

model_rf = RandomForestRegressor()
model_rf.fit(x_train, y_train)
y_pred_rf = model_rf.predict(x_test)

mse_rf = mean_squared_error(y_test, y_pred_rf)
print(f'Mean Squared Error RF: {mse_rf:.2f}')
rmse_rf = np.sqrt(mse_rf)
print(f'Root Mean Squared Error RF: {rmse_rf:.2f}')
mae_rf = mean_absolute_error(y_test, y_pred_rf)
print(f'Mean Absolute Error RF: {mae_rf:.2f}')
mape_rf = mean_absolute_percentage_error(y_test, y_pred_rf)
print(f'Mean Absolute Percentage Error RF: {mape_rf:.2f}')
r2_score_rf = r2_score(y_test, y_pred_rf)
print(f'R2 Score RF: {r2_score_rf:.2f}')

Mean Squared Error RF: 0.25
Root Mean Squared Error RF: 0.50
Mean Absolute Error RF: 0.33
Mean Absolute Percentage Error RF: 0.19
R2 Score RF: 0.81
